Importing The dependencies

In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [4]:
# loading the dataset to a Pandas Dataframe
credit_card_data = pd.read_csv('/content/sample_data/creditcard.csv')

In [5]:
# first 5 rows of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [6]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
281162,169976.0,1.982862,-0.191857,-1.288356,0.242522,0.211868,-0.374508,0.070290,-0.082566,0.300299,...,-0.184553,-0.466302,0.300574,0.719913,-0.229497,0.223967,-0.082091,-0.063403,21.39,0.0
281163,169976.0,-1.307438,-0.436296,1.382657,0.321161,0.526295,0.085972,0.668555,0.259204,-0.281912,...,0.041594,-0.465836,0.463291,-0.586186,-0.153310,-0.974211,0.069566,0.164605,196.74,0.0
281164,169976.0,-0.118356,0.999900,-0.489499,-1.194648,1.370202,-1.152867,1.633383,-0.369153,-0.888770,...,0.278934,0.845246,-0.448409,-0.345288,0.117910,0.169825,0.087010,0.139218,0.77,0.0
281165,169979.0,-1.058675,1.748133,-0.757358,-0.367130,0.555888,-1.274261,0.903275,-0.184630,0.331954,...,0.300303,1.098596,-0.152620,-0.150452,-0.408381,-0.205347,-0.231437,0.069091,2.64,0.0
281166,169979.0,-0.162987,1.348668,1.278697,4.398252,1.191563,2.071459,0.434193,0.424164,-1.950008,...,0.255804,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# dataset information
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 281167 entries, 0 to 281166
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    281167 non-null  float64
 1   V1      281167 non-null  float64
 2   V2      281167 non-null  float64
 3   V3      281167 non-null  float64
 4   V4      281167 non-null  float64
 5   V5      281167 non-null  float64
 6   V6      281167 non-null  float64
 7   V7      281167 non-null  float64
 8   V8      281167 non-null  float64
 9   V9      281167 non-null  float64
 10  V10     281167 non-null  float64
 11  V11     281167 non-null  float64
 12  V12     281167 non-null  float64
 13  V13     281167 non-null  float64
 14  V14     281167 non-null  float64
 15  V15     281167 non-null  float64
 16  V16     281167 non-null  float64
 17  V17     281167 non-null  float64
 18  V18     281167 non-null  float64
 19  V19     281167 non-null  float64
 20  V20     281167 non-null  float64
 21  V21     281167 non-null  float64
 22  V22     281167 non-null  float64
 23  V23     281166 non-null  float64
 24  V24     281166 non-null  float64
 25  V25     281166 non-null  float64
 26  V26     281166 non-null  float64
 27  V27     281166 non-null  float64
 28  V28     281166 non-null  float64
 29  Amount  281166 non-null  float64
 30  Class   281166 non-null  float64
dtypes: float64(31)
memory usage: 66.5 MB

In [8]:
# checking the number of the missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [10]:
# distribution of legit transaction & fraudlent transactions
credit_card_data['Class'].value_counts()

Class
0.0    280675
1.0       491
Name: count, dtype: int64

This Dataset is highly unblanced

0 -> Normal Transaction

1 -> fraudulent transaction

In [12]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data['Class'] == 1]

In [13]:
print(legit.shape)
print(fraud.shape)

(280675, 31)
(491, 31)

In [14]:
# statistical measure of the data
legit.Amount.describe()

count    280675.000000
mean         88.577648
std         250.183633
min           0.000000
25%           5.740000
50%          22.080000
75%          77.650000
max       25691.160000
Name: Amount, dtype: float64

In [15]:
fraud.Amount.describe()

count     491.000000
mean      122.373605
std       256.919810
min         0.000000
25%         1.000000
50%         9.210000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [16]:
# compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,93846.396662,0.007882,-0.011194,0.022541,-0.006101,0.001874,0.004298,0.008270,-0.001456,0.004395,...,-0.000423,-0.001405,-0.001153,-0.000589,-0.000105,0.001740,-0.000040,-0.000325,-0.000140,88.577648
1.0,80564.319756,-4.785724,3.630836,-7.042344,4.550447,-3.159987,-1.400386,-5.580527,0.571937,-2.587557,...,0.373114,0.715376,0.014679,-0.040243,-0.104427,0.040895,0.052343,0.170916,0.075853,122.373605

under-sampling

Build a sample dataset containing similar distribution of normal transaction and fraudulent Transactions

Number of fraudulent Transactions --> 492

In [17]:
legit_sample = legit.sample(n=492)

Concatenating two DataFrames

In [18]:
new_Dataset = pd.concat([legit_sample,fraud], axis=0)

In [19]:
new_Dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
263949,161194.0,2.072101,-0.114080,-1.143646,0.389853,-0.145989,-1.149267,0.125344,-0.278503,0.677091,...,-0.308496,-0.794108,0.331928,-0.133055,-0.306727,0.207861,-0.076342,-0.063213,1.79,0.0
115407,73865.0,-1.591460,-0.682997,1.405442,0.247970,-2.509725,0.509890,1.247513,0.404568,-0.008062,...,0.300621,0.027542,1.078674,0.398064,-0.138720,1.056704,-0.232360,0.069903,500.00,0.0
135950,81477.0,-1.896909,1.576144,0.467823,1.130605,-0.567694,2.033302,-1.195647,1.950590,0.289424,...,-0.339446,-0.787218,-0.158363,-1.716044,0.235871,-0.279702,0.050467,0.006911,20.33,0.0
170022,119980.0,-0.174907,1.151725,-0.159604,0.333851,1.097065,-1.011088,1.696611,-0.600881,-0.116476,...,0.046365,0.548817,-0.236413,-0.012359,0.239979,-0.597399,-0.108274,-0.146417,14.03,0.0
149435,91227.0,1.704074,-1.251913,-0.967380,-1.546390,-0.188629,0.953158,-0.914631,0.338666,3.327656,...,0.219753,0.889560,0.027529,-1.658117,-0.375328,-0.078023,0.020001,-0.057034,129.10,0.0

In [20]:
new_Dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
276864,167338.0,-1.374424,2.793185,-4.346572,2.400731,-1.688433,0.111136,-0.922038,-2.149930,-2.027474,...,-0.870779,0.504849,0.137994,0.368275,0.103137,-0.414209,0.454982,0.096711,349.08,1.0
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1.0
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1.0
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1.0
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1.0

In [24]:
new_Dataset['Class'].value_counts()

Class
0.0    492
1.0    491
Name: count, dtype: int64

In [26]:
new_Dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,92022.548780,0.041336,0.040575,0.107647,0.025329,-0.067584,-0.005663,0.031671,-0.056847,0.028792,...,0.014807,0.049844,-0.051919,0.017774,0.028079,-0.022136,0.000732,0.000646,0.004980,94.943659
1.0,80564.319756,-4.785724,3.630836,-7.042344,4.550447,-3.159987,-1.400386,-5.580527,0.571937,-2.587557,...,0.373114,0.715376,0.014679,-0.040243,-0.104427,0.040895,0.052343,0.170916,0.075853,122.373605

Splitting the data into features & Targets

In [27]:
X = new_Dataset.drop(columns='Class', axis=1)
Y = new_Dataset['Class']

In [28]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
263949  161194.0  2.072101 -0.114080 -1.143646  0.389853 -0.145989 -1.149267
115407   73865.0 -1.591460 -0.682997  1.405442  0.247970 -2.509725  0.509890
135950   81477.0 -1.896909  1.576144  0.467823  1.130605 -0.567694  2.033302
170022  119980.0 -0.174907  1.151725 -0.159604  0.333851  1.097065 -1.011088
149435   91227.0  1.704074 -1.251913 -0.967380 -1.546390 -0.188629  0.953158
...          ...       ...       ...       ...       ...       ...       ...
276864  167338.0 -1.374424  2.793185 -4.346572  2.400731 -1.688433  0.111136
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548

              V7        V8        V9  ...       V20       V21       V22  \
263949  0.125344 -0.278503  0.677091  ... -0.272722 -0.308496 -0.794108
115407  1.247513  0.404568 -0.008062  ...  1.070414  0.300621  0.027542
135950 -1.195647  1.950590  0.289424  ... -0.081542 -0.339446 -0.787218
170022  1.696611 -0.600881 -0.116476  ... -0.113515  0.046365  0.548817
149435 -0.914631  0.338666  3.327656  ... -0.092634  0.219753  0.889560
...          ...       ...       ...  ...       ...       ...       ...
276864 -0.922038 -2.149930 -2.027474  ...  0.650196 -0.870779  0.504849
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209

             V23       V24       V25       V26       V27       V28  Amount
263949  0.331928 -0.133055 -0.306727  0.207861 -0.076342 -0.063213    1.79
115407  1.078674  0.398064 -0.138720  1.056704 -0.232360  0.069903  500.00
135950 -0.158363 -1.716044  0.235871 -0.279702  0.050467  0.006911   20.33
170022 -0.236413 -0.012359  0.239979 -0.597399 -0.108274 -0.146417   14.03
149435  0.027529 -1.658117 -0.375328 -0.078023  0.020001 -0.057034  129.10
...          ...       ...       ...       ...       ...       ...     ...
276864  0.137994  0.368275  0.103137 -0.414209  0.454982  0.096711  349.08
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00

[983 rows x 30 columns]

In [32]:
print(Y)

263949    0.0
115407    0.0
135950    0.0
170022    0.0
149435    0.0
         ...
276864    1.0
279863    1.0
280143    1.0
280149    1.0
281144    1.0
Name: Class, Length: 983, dtype: float64

Split the data into training data & Testing Data

In [34]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, stratify=Y, random_state=42)

In [37]:
print(X.shape, X_train.shape, X_test.shape)

(983, 30) (786, 30) (197, 30)

Model Training

Logistic Regression

In [38]:
Model = LogisticRegression()

In [46]:
# training the logistic Regression Model with Training Data
Model.fit(X_train,Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

## Data Scaling

In [47]:
from sklearn.preprocessing import StandardScaler

In [48]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

Model Evaluation

Accuracy Score

In [50]:
# Accuracy on training Data
X_train_prediction =Model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [51]:
print('Accuracy on Training data: ', training_data_accuracy)

Accuracy on Training data:  0.9287531806615776

In [52]:
# accuracy on test data
X_test_prediction = Model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [53]:
print('Accuracy score on test Data : ', test_data_accuracy)

Accuracy score on test Data :  0.949238578680203